/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArcDialog.java
 *
 * Created on 27 juil. 2009, 13:28:53
 */

package Reseau;


/**
 *
 * @author HACIANE
 */
public class ArcDialog extends javax.swing.JDialog {

    public boolean valider=false;
    Reseau reseau;
    Arc arc;
    boolean ajout=true;
    public ArcDialog(java.awt.Frame parent, boolean modal, Reseau R, int arc_index) {
        super(parent, modal);
        initComponents();
        //////////////////////////////
        this.reseau=R;        
        this.JCBOrigine.setModel(new ListeCarCBModel(reseau));
        this.JCBCible.setModel(new ListeCarCBModel(reseau));
        if(arc_index>=0){
          this.ajout=false;
          this.arc=this.reseau.ListeArcs.get(arc_index);
          /// remplissage des champs
          this.JTFCod.setText(Integer.toString(arc.code_arc));
          this.JTFDebit.setText(Float.toString(arc.debit));
          this.JTFLong.setText(Integer.toString(arc.longueur));
          //this.JTFNbreLignes.setText(Integer.toString(arc.nbre_lignes));
          this.JTFVM.setText(Integer.toString(arc.vitesse_moyenne));
          if(this.arc.Origine!=null){
              this.JCBOrigine.setSelectedIndex(this.reseau.Rech_Pos_Carrefour(arc.Origine.code_carrefour)+1);
          }else{
              this.JCBOrigine.setSelectedIndex(0);
          }
          if(this.arc.Des!=null){
              this.JCBCible.setSelectedIndex(this.reseau.Rech_Pos_Carrefour(arc.Des.code_carrefour)+1);
          }else{
              this.JCBCible.setSelectedIndex(0);
          }
        }else{
            this.arc=new Arc(0,0,0,0,0,null,null);
        }
        ListeSuivantTabModel model=new ListeSuivantTabModel(arc);
        this.JTABListeSuiv.setModel(model);
        this.setModal(modal);
        this.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABListeSuiv = new javax.swing.JTable();
        JBAjouterSuiv = new javax.swing.JButton();
        JBSuppSuiv = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JBValider = new javax.swing.JButton();
        JBAnnuler = new javax.swing.JButton();
        JTFCod = new javax.swing.JTextField();
        JTFLong = new javax.swing.JTextField();
        JTFVM = new javax.swing.JTextField();
        JTFDebit = new javax.swing.JTextField();
        JCBOrigine = new javax.swing.JComboBox();
        JCBCible = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arc");

        jLabel1.setText("Code arc:");

        jLabel2.setText("Longueur:");

        jLabel3.setText("Vitesse moyenne:");

        jLabel5.setText("Débit de sortie:");

        jLabel6.setText("Origine:");

        jLabel7.setText("Cible:");

        jLabel8.setBackground(new java.awt.Color(102, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Liste des suivants");
        jLabel8.setOpaque(true);

        JTABListeSuiv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTABListeSuiv);

        JBAjouterSuiv.setText("+");
        JBAjouterSuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterSuivActionPerformed(evt);
            }
        });

        JBSuppSuiv.setText("-");
        JBSuppSuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSuppSuivActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JBValider.setText("Valider");
        JBValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBValiderActionPerformed(evt);
            }
        });

        JBAnnuler.setText("Annuler");
        JBAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(JBAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBValider, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBValider)
                    .addComponent(JBAnnuler))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        JTFLong.setText("300");

        JTFVM.setText("40");

        JTFDebit.setText("0.6");

        JCBOrigine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JCBCible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Entier");

        jLabel10.setText("en mètres");

        jLabel11.setText("Km/h");

        jLabel12.setText("véhicule/s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTFDebit)
                            .addComponent(JTFVM)
                            .addComponent(JTFLong)
                            .addComponent(JTFCod, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(109, 109, 109)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JCBCible, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JCBOrigine, 0, 139, Short.MAX_VALUE))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBSuppSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBAjouterSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFDebit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JCBOrigine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JCBCible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterSuiv)
                    .addComponent(JBSuppSuiv))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBValiderActionPerformed
        // TODO add your handling code here:
        try{
          int cod=Integer.valueOf(this.JTFCod.getText());
          int lon=Integer.valueOf(this.JTFLong.getText());
          int VM=Integer.valueOf(this.JTFVM.getText());         
          int nbre_l=1;//Integer.valueOf(this.JTFNbreLignes.getText());
          float debit=Float.valueOf(this.JTFDebit.getText());
          int o=this.JCBOrigine.getSelectedIndex();
          Carrefour origine=null;
          if(o>0){
            origine=this.reseau.ListeCarrefour.get(o-1);
          }
          int ci=this.JCBCible.getSelectedIndex();
          Carrefour cible=null;
          if(ci>0){
              cible=this.reseau.ListeCarrefour.get(ci-1);
          }
          //////////////// init de l'arc //////////////////////
          if(! this.ajout){
              this.reseau.supp_arc(arc.code_arc);
          }
          arc.Des=cible;
          arc.Origine=origine;
          arc.code_arc=cod;
          arc.debit=debit;
          arc.longueur=lon;
          arc.capacite=lon/arc.long_cel;
          arc.nbre_lignes=nbre_l;
          arc.vitesse_moyenne=VM;
          arc.creer_cel();
          //if(this.ajout){
          this.reseau.Ajouter_Arc(arc);
          //}
          this.valider=true;
          this.dispose();
        }catch(Exception e){
            //System.out.println(e.toString());
        }
    }//GEN-LAST:event_JBValiderActionPerformed

    private void JBAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAnnulerActionPerformed
        // TODO add your handling code here:
        this.valider=false;
        this.dispose();
    }//GEN-LAST:event_JBAnnulerActionPerformed

    private void JBAjouterSuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterSuivActionPerformed
        // TODO add your handling code here:
        ListeArcsDialog dialog=new ListeArcsDialog(null, true, reseau);
        if(dialog.valider){
            for(int i=0;i<dialog.selection.length;i++){
                this.arc.Ajouter_Suivant(this.reseau.ListeArcs.get(dialog.selection[i]),10);
                

            }
            ((ListeSuivantTabModel)this.JTABListeSuiv.getModel()).raffraichir();
            
        }
        
    }//GEN-LAST:event_JBAjouterSuivActionPerformed

    private void JBSuppSuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSuppSuivActionPerformed
        // TODO add your handling code here:
        int i=this.JTABListeSuiv.getSelectedRow();
        if(i>=0){
            this.arc.suivants.removeElementAt(i);
            this.arc.Calculer_Proportions();
            ((ListeSuivantTabModel)this.JTABListeSuiv.getModel()).raffraichir();
        }

    }//GEN-LAST:event_JBSuppSuivActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAjouterSuiv;
    private javax.swing.JButton JBAnnuler;
    private javax.swing.JButton JBSuppSuiv;
    private javax.swing.JButton JBValider;
    private javax.swing.JComboBox JCBCible;
    private javax.swing.JComboBox JCBOrigine;
    private javax.swing.JTable JTABListeSuiv;
    private javax.swing.JTextField JTFCod;
    private javax.swing.JTextField JTFDebit;
    private javax.swing.JTextField JTFLong;
    private javax.swing.JTextField JTFVM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
