/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fen.java
 *
 * Created on 31 août 2009, 21:37:12
 */

package Reseau;

import Reseau.FrequencesPassageBus.InfoFreqLigne;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.ui.RectangleInsets;

/**
 *
 * @author HACIANE
 */
public class FrequencesFrame extends javax.swing.JFrame {

    XYDataset data1;
    Reseau R;
    List charts;
    FrequencesPassageBus F;
    /** Creates new form Fen */
    
    public FrequencesFrame(FrequencesPassageBus f) {
        initComponents();
        this.setTitle("Fréquences de passage des bus");
        this.setVisible(true);
        charts = new ArrayList();
        this.F=f;
        this.Afficher_graphe();

    }
    private void Afficher_graphe(){
        data1 = createSampleData();
        jtabbedpane.removeAll();
        jtabbedpane.add("Splines:", createChartPanel1());
        jtabbedpane.add("Lines:", createChartPanel2());
    }
    public void addChart(JFreeChart jfreechart) {
        charts.add(jfreechart);
    }

    public JFreeChart[] getCharts() {
        int i = charts.size();
        JFreeChart ajfreechart[] = new JFreeChart[i];
        for (int j = 0; j < i; j++) {
            ajfreechart[j] = (JFreeChart)charts.get(j);
        }

        return ajfreechart;
    }

    
    private ChartPanel createChartPanel1() {
            NumberAxis numberaxis = new NumberAxis("Temps (en seconde) ");
            numberaxis.setAutoRangeIncludesZero(false);
            NumberAxis numberaxis1 = new NumberAxis("Retard(%)");
            numberaxis1.setAutoRangeIncludesZero(false);
            XYSplineRenderer xysplinerenderer = new XYSplineRenderer();
            XYPlot xyplot = new XYPlot(data1, numberaxis, numberaxis1, xysplinerenderer);
            xyplot.setBackgroundPaint(Color.lightGray);
            xyplot.setDomainGridlinePaint(Color.white);
            xyplot.setRangeGridlinePaint(Color.white);
            xyplot.setAxisOffset(new RectangleInsets(4D, 4D, 4D, 4D));
            JFreeChart jfreechart = new JFreeChart("Retard en fonction du temps", JFreeChart.DEFAULT_TITLE_FONT, xyplot, true);
            addChart(jfreechart);
            ChartUtilities.applyCurrentTheme(jfreechart);
            ChartPanel chartpanel = new ChartPanel(jfreechart);
            return chartpanel;
        }
    private ChartPanel createChartPanel2() {
            NumberAxis numberaxis = new NumberAxis("Temps (en seconde)");
            numberaxis.setAutoRangeIncludesZero(false);
            NumberAxis numberaxis1 = new NumberAxis("Retard(%)");
            numberaxis1.setAutoRangeIncludesZero(false);
            XYLineAndShapeRenderer xylineandshaperenderer = new XYLineAndShapeRenderer();
            XYPlot xyplot = new XYPlot(data1, numberaxis, numberaxis1, xylineandshaperenderer);
            xyplot.setBackgroundPaint(Color.lightGray);
            xyplot.setDomainGridlinePaint(Color.white);
            xyplot.setRangeGridlinePaint(Color.white);
            xyplot.setAxisOffset(new RectangleInsets(4D, 4D, 4D, 4D));
            JFreeChart jfreechart = new JFreeChart("Retard en fonction du temps", JFreeChart.DEFAULT_TITLE_FONT, xyplot, true);
            addChart(jfreechart);
            ChartUtilities.applyCurrentTheme(jfreechart);
            ChartPanel chartpanel = new ChartPanel(jfreechart);
            return chartpanel;
        }
    private XYDataset createSampleData() {        
        InfoFreqLigne L;
        XYSeriesCollection xyseriescollection = new XYSeriesCollection();
        for(int i=0;i<this.F.ListeFrequences.size();i++){
            L=F.ListeFrequences.elementAt(i);
            XYSeries xyseries = new XYSeries(L.cod_ligne);
            for(int j=0;j<L.frequences.size();j++){
                xyseries.add(L.frequences.elementAt(j).date, L.frequences.elementAt(j).f);
            }
            xyseriescollection.addSeries(xyseries);
        }
        return xyseriescollection;                               
        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtabbedpane = new javax.swing.JTabbedPane();
        JBRaffraichir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JBRaffraichir.setText("Raffraichir");
        JBRaffraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRaffraichirActionPerformed(evt);
            }
        });

        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtabbedpane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBRaffraichir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtabbedpane, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBRaffraichir)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBRaffraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRaffraichirActionPerformed
       
        this.Afficher_graphe();
    }//GEN-LAST:event_JBRaffraichirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBRaffraichir;
    private javax.swing.JButton jButton2;
    private javax.swing.JTabbedPane jtabbedpane;
    // End of variables declaration//GEN-END:variables
  

}
