/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GestionReseau.java
 *
 */

package Reseau;

import Agents.AgentReseau;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Dihya
 */
public class GestionReseau extends javax.swing.JFrame {

    //////////////////////////////////////
	public Reseau R;
    //AgentContainer ac;
    public Config config;
	ListeArcTabModel LATM;
	ListeCarrTabModel LCTA;
    SourceVehTabModel LSTM;
	ListeArcTabModel LAE_Model=null;
	ListeArcTabModel LAS_Model=null;
    AgentReseau AR;
    Vector<String> ListeLigne;
	//////////////////////////////////////
    
    public GestionReseau(AgentReseau ar, Config conf) {
        initComponents();
        this.ListeLigne=ar.ListeLigne;
        this.AR=ar;
        this.config=conf;        
        this.R=conf.R;        
        this.Initialiser();
        this.setExtendedState(this.getExtendedState() | GestionReseau.MAXIMIZED_BOTH);
        this.setVisible(true);
    }   

    /////////////////////////////////////////////////////////
	private void Initialiser() {
		LATM=new ListeArcTabModel(R.ListeArcs, "Liste des arcs");
		LCTA=new ListeCarrTabModel(R.ListeCarrefour);
        this.LSTM=new SourceVehTabModel(this.R.ListeDesSources);
		this.JTABListeArcs.setModel(this.LATM);
		this.JTABListeCarrefours.setModel(this.LCTA);
        this.JTabListeSources.setModel(LSTM);
       

	}

    public int Rech_Nom_Car(Carrefour c){
        return c.code_carrefour;
     
    }
    public int Rech_coord_x(int f){
        int corx=0;
        int i=this.JTABListeCarrefours.getSelectedRow();
        if(i>=0){
       if (f== this.LCTA.LC.elementAt(i).code_carrefour)
       {
             corx= this.LCTA.LC.elementAt(i).coor_x;
             
        }
        
    }
        return corx;
    }
        public int Rech_coord_y(int f){
            int cory=0;
        int i=this.JTABListeCarrefours.getSelectedRow();
        if(i>=0){
       if (f== this.LCTA.LC.elementAt(i).code_carrefour)
       {
          
             cory= this.LCTA.LC.elementAt(i).coor_y;
        }
        
    }
        return cory;
    }
	void AjouterCarrefour(){
            
		String f = (String)JOptionPane.showInputDialog(
				   this,
                   
                        
                        
				   "Saisir le nom du carrefour � ajouter",
				   "Ajout de nouveau carrefour",
				   JOptionPane.QUESTION_MESSAGE,
				   null,
				   null, // c'est ouvert !!!
				   null); // valeur initiale
                int s= Integer.parseInt(f);
                if ((f != null) && (f.length() > 0) && (R.Rech_Carrefour(s)==null)){
                 
            	
		int cor_x= Rech_coord_x(s);
                int cor_y=Rech_coord_y(s);
			this.R.Ajouter_Carrefour(s, cor_x, cor_y);
            this.AR.AjouterAgentCarrefour(s);
			this.LCTA.fireTableDataChanged();
                }else{
            //System.out.println("le carrefour "+s+" n'est pas créé !!");
        }

	}
	void Afficher_Arc_Carrefour(){
		int index=this.JTABListeCarrefours.getSelectedRow();
		if (index>=0){
			this.LAE_Model=new ListeArcTabModel(this.R.ListeCarrefour.get(index).E, "code arc entrant");
			this.LAS_Model=new ListeArcTabModel(this.R.ListeCarrefour.get(index).S, "code arc sotrant");
			this.JTABArcsEn.setModel(LAE_Model);
			this.JTABArcsSor.setModel(LAS_Model);
		}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * 
     */
         /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABListeCarrefours = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTABArcsEn = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTABArcsSor = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JBAfficherCarr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTABListeArcs = new javax.swing.JTable();
        JBAjouterArc = new javax.swing.JButton();
        JBSuppArc = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JBModifierarc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTabListeSources = new javax.swing.JTable();
        JBAjouterSource = new javax.swing.JButton();
        JBSupprimerSource = new javax.swing.JButton();
        JMenuBar = new javax.swing.JMenuBar();
        JMenuFichier = new javax.swing.JMenu();
        JMIOuvrir = new javax.swing.JMenuItem();
        JMINouveau = new javax.swing.JMenuItem();
        JMIEnregister = new javax.swing.JMenuItem();
        JMISaveAs = new javax.swing.JMenuItem();
        JMIExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JMIvisualiser = new javax.swing.JMenuItem();
        JMILIgnebus = new javax.swing.JMenuItem();
        JMIRetardVeh = new javax.swing.JMenuItem();
        JMIRetardBus = new javax.swing.JMenuItem();
        JMIRetardBusEtVeh = new javax.swing.JMenuItem();
        JMIHistor = new javax.swing.JMenuItem();
        JMactions = new javax.swing.JMenu();
        JMIArretertousSource = new javax.swing.JMenuItem();
        JMIDemarrerTous = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion du réseau");
        getContentPane().setLayout(new java.awt.GridLayout(1, 3, 3, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JTABListeCarrefours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTABListeCarrefours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABListeCarrefoursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABListeCarrefours);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Supprimer");

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        JTABArcsEn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(JTABArcsEn);

        jPanel3.add(jScrollPane4);

        JTABArcsSor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(JTABArcsSor);

        jPanel3.add(jScrollPane3);

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des carrefours");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addContainerGap()))
        );

        JBAfficherCarr.setText("Afficher");
        JBAfficherCarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAfficherCarrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBAfficherCarr, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBAfficherCarr))
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JTABListeArcs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTABListeArcs);

        JBAjouterArc.setText("Ajouter");
        JBAjouterArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterArcActionPerformed(evt);
            }
        });

        JBSuppArc.setText("Supprimer");
        JBSuppArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSuppArcActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 204, 255));

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Liste des arcs");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap()))
        );

        JBModifierarc.setText("Modifier");
        JBModifierarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModifierarcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JBAjouterArc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBModifierarc, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBSuppArc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSuppArc)
                    .addComponent(JBAjouterArc)
                    .addComponent(JBModifierarc))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Liste des sources");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTabListeSources.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(JTabListeSources);

        JBAjouterSource.setText("Ajouter");
        JBAjouterSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterSourceActionPerformed(evt);
            }
        });

        JBSupprimerSource.setText("Supprimer");
        JBSupprimerSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerSourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(JBAjouterSource, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(JBSupprimerSource, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterSource)
                    .addComponent(JBSupprimerSource))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);

        JMenuFichier.setText("Fichier");

        JMIOuvrir.setText("Ouvrir");
        JMIOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIOuvrirActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMIOuvrir);

        JMINouveau.setText("Nouveau");
        JMINouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMINouveauActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMINouveau);

        JMIEnregister.setText("Enregister");
        JMIEnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIEnregisterActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMIEnregister);

        JMISaveAs.setText("Enregistrer sous");
        JMISaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMISaveAsActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMISaveAs);

        JMIExit.setText("Quitter");
        JMIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIExitActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMIExit);

        JMenuBar.add(JMenuFichier);

        jMenu1.setText("Affichage");

        JMIvisualiser.setText("Visualiser");
        JMIvisualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIvisualiserActionPerformed(evt);
            }
        });
        jMenu1.add(JMIvisualiser);

        JMILIgnebus.setText("Gestion des lignes");
        JMILIgnebus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMILIgnebusActionPerformed(evt);
            }
        });
        jMenu1.add(JMILIgnebus);

        JMIRetardVeh.setText("Retard des véhicules");
        JMIRetardVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIRetardVehActionPerformed(evt);
            }
        });
        jMenu1.add(JMIRetardVeh);

        JMIRetardBus.setText("Retard des bus");
        JMIRetardBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIRetardBusActionPerformed(evt);
            }
        });
        jMenu1.add(JMIRetardBus);

        JMIRetardBusEtVeh.setText("Retard Bus+véhicules");
        JMIRetardBusEtVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIRetardBusEtVehActionPerformed(evt);
            }
        });
        jMenu1.add(JMIRetardBusEtVeh);

        JMIHistor.setText("Historiques des plans");
        JMIHistor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIHistorActionPerformed(evt);
            }
        });
        jMenu1.add(JMIHistor);

        JMenuBar.add(jMenu1);

        JMactions.setText("Actions");

        JMIArretertousSource.setText("Arrêter toutes les sources");
        JMIArretertousSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIArretertousSourceActionPerformed(evt);
            }
        });
        JMactions.add(JMIArretertousSource);

        JMIDemarrerTous.setText("Démarrer toutes les sources");
        JMIDemarrerTous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIDemarrerTousActionPerformed(evt);
            }
        });
        JMactions.add(JMIDemarrerTous);

        JMenuBar.add(JMactions);

        setJMenuBar(JMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.AjouterCarrefour();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTABListeCarrefoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABListeCarrefoursMouseClicked
        
        this.Afficher_Arc_Carrefour();
    }//GEN-LAST:event_JTABListeCarrefoursMouseClicked

    private void JBAjouterArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterArcActionPerformed
        
        ArcDialog dial=new ArcDialog(this, true, R, -1);
        ((ListeArcTabModel)this.JTABListeArcs.getModel()).fireTableDataChanged();

    }//GEN-LAST:event_JBAjouterArcActionPerformed

    private void JBAjouterSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterSourceActionPerformed
        // verifier que l'arc n'a aucun precedent (origine=null)
        DialAjoutSource dial=new DialAjoutSource(this, true, R.ListeArcs);
        if(dial.valide){
            if(R.Rech_Arc(dial.cod_arc).Origine==null){
              R.Ajouter_Source(dial.cod_src, dial.periode, dial.cod_arc);
              this.LSTM.fireTableDataChanged();
            }else{
                JOptionPane.showMessageDialog(this,
                        "Une source ne peut etre créée que sur un arc extrémité !",
                        "Erreur ",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_JBAjouterSourceActionPerformed

    private void JBModifierarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModifierarcActionPerformed
        int i=this.JTABListeArcs.getSelectedRow();
        if(i>=0){
            ArcDialog dial=new ArcDialog(this, true, R, i);
            ((ListeArcTabModel)this.JTABListeArcs.getModel()).fireTableDataChanged();
        }
    }//GEN-LAST:event_JBModifierarcActionPerformed

    private void JMIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMIExitActionPerformed

    private void JMIEnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIEnregisterActionPerformed
        this.AR.save();
    }//GEN-LAST:event_JMIEnregisterActionPerformed

    private void JBSuppArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSuppArcActionPerformed
        int i=this.JTABListeArcs.getSelectedRow();
        if(i>=0){
            this.R.supp_arc(this.LATM.LA.elementAt(i).code_arc);
            this.LATM.fireTableDataChanged();
        }
    }//GEN-LAST:event_JBSuppArcActionPerformed
     private void JBAfficherCarrActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        int i=this.JTABListeCarrefours.getSelectedRow();
        if(i>=0){
            int nom=this.LCTA.LC.elementAt(i).code_carrefour;
            int cor_x= this.LCTA.LC.elementAt(i).coor_x;
             int cor_y= this.LCTA.LC.elementAt(i).coor_y;
            this.AR.Affichier_Interface(Integer.toString(nom));
        }
    }    



    private void JMIvisualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIvisualiserActionPerformed
        new FenSim(this.AR, this.config);
    }//GEN-LAST:event_JMIvisualiserActionPerformed

    private void JMILIgnebusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMILIgnebusActionPerformed

        new ListeDesLignesJFrame(ListeLigne, AR);
        
    }//GEN-LAST:event_JMILIgnebusActionPerformed

    private void JMINouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMINouveauActionPerformed
        // TODO add your handling code here:
        this.AR.nouveau();
    }//GEN-LAST:event_JMINouveauActionPerformed

    private void JMIOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIOuvrirActionPerformed
        this.AR.ouvrir();

    }//GEN-LAST:event_JMIOuvrirActionPerformed

    private void JMIRetardVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIRetardVehActionPerformed
       new Fen(this.R, 'v');

    }//GEN-LAST:event_JMIRetardVehActionPerformed

    private void JMISaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMISaveAsActionPerformed
        this.AR.save_as();
    }//GEN-LAST:event_JMISaveAsActionPerformed

    private void JBSupprimerSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerSourceActionPerformed
        int index=this.JTabListeSources.getSelectedRow();
        if(index>=0){
            this.config.R.ListeDesSources.elementAt(index).arreter_source();
            this.config.R.ListeDesSources.removeElementAt(index);
            this.LSTM.fireTableRowsDeleted(index,index);
        }
    }//GEN-LAST:event_JBSupprimerSourceActionPerformed

    private void JMIArretertousSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIArretertousSourceActionPerformed
        for(int i=0; i<this.config.R.ListeDesSources.size(); i++){                     
                this.config.R.ListeDesSources.elementAt(i).arc.occuper(0, 'v');
        }
    }//GEN-LAST:event_JMIArretertousSourceActionPerformed

    private void JMIDemarrerTousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIDemarrerTousActionPerformed
        for(int i=0; i<this.config.R.ListeDesSources.size(); i++){
            if(this.config.R.ListeDesSources.elementAt(i).arc.ListeCellules.elementAt(0).oqp){
                this.config.R.ListeDesSources.elementAt(i).arc.liberer(0, 'v');
            }
        }
    }//GEN-LAST:event_JMIDemarrerTousActionPerformed

    private void JMIRetardBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIRetardBusActionPerformed
        new Fen(this.R, 'b');
    }//GEN-LAST:event_JMIRetardBusActionPerformed

    private void JMIHistorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIHistorActionPerformed
        this.AR.afficher_historique();
    }//GEN-LAST:event_JMIHistorActionPerformed

    private void JMIRetardBusEtVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIRetardBusEtVehActionPerformed
        new Fen(this.R, 'e');
    }//GEN-LAST:event_JMIRetardBusEtVehActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAfficherCarr;
    private javax.swing.JButton JBAjouterArc;
    private javax.swing.JButton JBAjouterSource;
    private javax.swing.JButton JBModifierarc;
    private javax.swing.JButton JBSuppArc;
    private javax.swing.JButton JBSupprimerSource;
    private javax.swing.JMenuItem JMIArretertousSource;
    private javax.swing.JMenuItem JMIDemarrerTous;
    private javax.swing.JMenuItem JMIEnregister;
    private javax.swing.JMenuItem JMIExit;
    private javax.swing.JMenuItem JMIHistor;
    private javax.swing.JMenuItem JMILIgnebus;
    private javax.swing.JMenuItem JMINouveau;
    private javax.swing.JMenuItem JMIOuvrir;
    private javax.swing.JMenuItem JMIRetardBus;
    private javax.swing.JMenuItem JMIRetardBusEtVeh;
    private javax.swing.JMenuItem JMIRetardVeh;
    private javax.swing.JMenuItem JMISaveAs;
    private javax.swing.JMenuItem JMIvisualiser;
    private javax.swing.JMenu JMactions;
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JMenu JMenuFichier;
    private javax.swing.JTable JTABArcsEn;
    private javax.swing.JTable JTABArcsSor;
    private javax.swing.JTable JTABListeArcs;
    private javax.swing.JTable JTABListeCarrefours;
    private javax.swing.JTable JTabListeSources;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

}

        /*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABListeCarrefours = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTABArcsEn = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTABArcsSor = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JBAfficherCarr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTABListeArcs = new javax.swing.JTable();
        JBAjouterArc = new javax.swing.JButton();
        JBSuppArc = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JBModifierarc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTabListeSources = new javax.swing.JTable();
        JBAjouterSource = new javax.swing.JButton();
        JBSupprimerSource = new javax.swing.JButton();
        JMenuBar = new javax.swing.JMenuBar();
        JMenuFichier = new javax.swing.JMenu();
        JMIOuvrir = new javax.swing.JMenuItem();
        JMINouveau = new javax.swing.JMenuItem();
        JMIEnregister = new javax.swing.JMenuItem();
        JMISaveAs = new javax.swing.JMenuItem();
        JMIExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JMIvisualiser = new javax.swing.JMenuItem();
        JMILIgnebus = new javax.swing.JMenuItem();
        JMIRetardVeh = new javax.swing.JMenuItem();
        JMIRetardBus = new javax.swing.JMenuItem();
        JMIRetardBusEtVeh = new javax.swing.JMenuItem();
        JMIHistor = new javax.swing.JMenuItem();
        JMactions = new javax.swing.JMenu();
        JMIArretertousSource = new javax.swing.JMenuItem();
        JMIDemarrerTous = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion du réseau");
        getContentPane().setLayout(new java.awt.GridLayout(1, 3, 3, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JTABListeCarrefours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTABListeCarrefours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABListeCarrefoursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABListeCarrefours);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Supprimer");

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        JTABArcsEn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(JTABArcsEn);

        jPanel3.add(jScrollPane4);

        JTABArcsSor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(JTABArcsSor);

        jPanel3.add(jScrollPane3);

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des carrefours");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addContainerGap()))
        );

        JBAfficherCarr.setText("Afficher");
        JBAfficherCarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAfficherCarrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBAfficherCarr, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBAfficherCarr))
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JTABListeArcs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTABListeArcs);

        JBAjouterArc.setText("Ajouter");
        JBAjouterArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterArcActionPerformed(evt);
            }
        });

        JBSuppArc.setText("Supprimer");
        JBSuppArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSuppArcActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 204, 255));

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Liste des arcs");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap()))
        );

        JBModifierarc.setText("Modifier");
        JBModifierarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModifierarcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JBAjouterArc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBModifierarc, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBSuppArc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSuppArc)
                    .addComponent(JBAjouterArc)
                    .addComponent(JBModifierarc))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Liste des sources");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTabListeSources.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(JTabListeSources);

        JBAjouterSource.setText("Ajouter");
        JBAjouterSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterSourceActionPerformed(evt);
            }
        });

        JBSupprimerSource.setText("Supprimer");
        JBSupprimerSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSupprimerSourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(JBAjouterSource, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(JBSupprimerSource, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterSource)
                    .addComponent(JBSupprimerSource))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);

        JMenuFichier.setText("Fichier");

        JMIOuvrir.setText("Ouvrir");
        JMIOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIOuvrirActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMIOuvrir);

        JMINouveau.setText("Nouveau");
        JMINouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMINouveauActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMINouveau);

        JMIEnregister.setText("Enregister");
        JMIEnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIEnregisterActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMIEnregister);

        JMISaveAs.setText("Enregistrer sous");
        JMISaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMISaveAsActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMISaveAs);

        JMIExit.setText("Quitter");
        JMIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIExitActionPerformed(evt);
            }
        });
        JMenuFichier.add(JMIExit);

        JMenuBar.add(JMenuFichier);

        jMenu1.setText("Affichage");

        JMIvisualiser.setText("Visualiser");
        JMIvisualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIvisualiserActionPerformed(evt);
            }
        });
        jMenu1.add(JMIvisualiser);

        JMILIgnebus.setText("Gestion des lignes");
        JMILIgnebus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMILIgnebusActionPerformed(evt);
            }
        });
        jMenu1.add(JMILIgnebus);

        JMIRetardVeh.setText("Retard des véhicules");
        JMIRetardVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIRetardVehActionPerformed(evt);
            }
        });
        jMenu1.add(JMIRetardVeh);

        JMIRetardBus.setText("Retard des bus");
        JMIRetardBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIRetardBusActionPerformed(evt);
            }
        });
        jMenu1.add(JMIRetardBus);

        JMIRetardBusEtVeh.setText("Retard Bus+véhicules");
        JMIRetardBusEtVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIRetardBusEtVehActionPerformed(evt);
            }
        });
        jMenu1.add(JMIRetardBusEtVeh);

        JMIHistor.setText("Historiques des plans");
        JMIHistor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIHistorActionPerformed(evt);
            }
        });
        jMenu1.add(JMIHistor);

        JMenuBar.add(jMenu1);

        JMactions.setText("Actions");

        JMIArretertousSource.setText("Arrêter toutes les sources");
        JMIArretertousSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIArretertousSourceActionPerformed(evt);
            }
        });
        JMactions.add(JMIArretertousSource);

        JMIDemarrerTous.setText("Démarrer toutes les sources");
        JMIDemarrerTous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIDemarrerTousActionPerformed(evt);
            }
        });
        JMactions.add(JMIDemarrerTous);

        JMenuBar.add(JMactions);

        setJMenuBar(JMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.AjouterCarrefour();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTABListeCarrefoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABListeCarrefoursMouseClicked
        
        this.Afficher_Arc_Carrefour();
    }//GEN-LAST:event_JTABListeCarrefoursMouseClicked

    private void JBAjouterArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterArcActionPerformed
        
        ArcDialog dial=new ArcDialog(this, true, R, -1);
        ((ListeArcTabModel)this.JTABListeArcs.getModel()).fireTableDataChanged();

    }//GEN-LAST:event_JBAjouterArcActionPerformed

    private void JBAjouterSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterSourceActionPerformed
        // verifier que l'arc n'a aucun precedent (origine=null)
        DialAjoutSource dial=new DialAjoutSource(this, true, R.ListeArcs);
        if(dial.valide){
            if(R.Rech_Arc(dial.cod_arc).Origine==null){
              R.Ajouter_Source(dial.cod_src, dial.periode, dial.cod_arc);
              this.LSTM.fireTableDataChanged();
            }else{
                JOptionPane.showMessageDialog(this,
                        "Une source ne peut etre créée que sur un arc extrémité !",
                        "Erreur ",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_JBAjouterSourceActionPerformed

    private void JBModifierarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModifierarcActionPerformed
        int i=this.JTABListeArcs.getSelectedRow();
        if(i>=0){
            ArcDialog dial=new ArcDialog(this, true, R, i);
            ((ListeArcTabModel)this.JTABListeArcs.getModel()).fireTableDataChanged();
        }
    }//GEN-LAST:event_JBModifierarcActionPerformed

    private void JMIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMIExitActionPerformed

    private void JMIEnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIEnregisterActionPerformed
        this.AR.save();
    }//GEN-LAST:event_JMIEnregisterActionPerformed

    private void JBSuppArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSuppArcActionPerformed
        int i=this.JTABListeArcs.getSelectedRow();
        if(i>=0){
            this.R.supp_arc(this.LATM.LA.elementAt(i).code_arc);
            this.LATM.fireTableDataChanged();
        }
    }//GEN-LAST:event_JBSuppArcActionPerformed

    private void JBAfficherCarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAfficherCarrActionPerformed
        // TODO add your handling code here:
        int i=this.JTABListeCarrefours.getSelectedRow();
        if(i>=0){
            int nom=this.LCTA.LC.elementAt(i).code_carrefour;
            int cor_x= this.LCTA.LC.elementAt(i).coor_x;
             int cor_y= this.LCTA.LC.elementAt(i).coor_y;
            this.AR.Affichier_Interface(Integer.toString(nom));
        }
    }//GEN-LAST:event_JBAfficherCarrActionPerformed

    private void JMIvisualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIvisualiserActionPerformed
        new FenSim(this.AR, this.config);
    }//GEN-LAST:event_JMIvisualiserActionPerformed

    private void JMILIgnebusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMILIgnebusActionPerformed

        new ListeDesLignesJFrame(ListeLigne, AR);
        
    }//GEN-LAST:event_JMILIgnebusActionPerformed

    private void JMINouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMINouveauActionPerformed
        // TODO add your handling code here:
        this.AR.nouveau();
    }//GEN-LAST:event_JMINouveauActionPerformed

    private void JMIOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIOuvrirActionPerformed
        this.AR.ouvrir();

    }//GEN-LAST:event_JMIOuvrirActionPerformed

    private void JMIRetardVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIRetardVehActionPerformed
       new Fen(this.R, 'v');

    }//GEN-LAST:event_JMIRetardVehActionPerformed

    private void JMISaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMISaveAsActionPerformed
        this.AR.save_as();
    }//GEN-LAST:event_JMISaveAsActionPerformed

    private void JBSupprimerSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSupprimerSourceActionPerformed
        int index=this.JTabListeSources.getSelectedRow();
        if(index>=0){
            this.config.R.ListeDesSources.elementAt(index).arreter_source();
            this.config.R.ListeDesSources.removeElementAt(index);
            this.LSTM.fireTableRowsDeleted(index,index);
        }
    }//GEN-LAST:event_JBSupprimerSourceActionPerformed

    private void JMIArretertousSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIArretertousSourceActionPerformed
        for(int i=0; i<this.config.R.ListeDesSources.size(); i++){                     
                this.config.R.ListeDesSources.elementAt(i).arc.occuper(0, 'v');
        }
    }//GEN-LAST:event_JMIArretertousSourceActionPerformed

    private void JMIDemarrerTousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIDemarrerTousActionPerformed
        for(int i=0; i<this.config.R.ListeDesSources.size(); i++){
            if(this.config.R.ListeDesSources.elementAt(i).arc.ListeCellules.elementAt(0).oqp){
                this.config.R.ListeDesSources.elementAt(i).arc.liberer(0, 'v');
            }
        }
    }//GEN-LAST:event_JMIDemarrerTousActionPerformed

    private void JMIRetardBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIRetardBusActionPerformed
        new Fen(this.R, 'b');
    }//GEN-LAST:event_JMIRetardBusActionPerformed

    private void JMIHistorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIHistorActionPerformed
        this.AR.afficher_historique();
    }//GEN-LAST:event_JMIHistorActionPerformed

    private void JMIRetardBusEtVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIRetardBusEtVehActionPerformed
        new Fen(this.R, 'e');
    }//GEN-LAST:event_JMIRetardBusEtVehActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAfficherCarr;
    private javax.swing.JButton JBAjouterArc;
    private javax.swing.JButton JBAjouterSource;
    private javax.swing.JButton JBModifierarc;
    private javax.swing.JButton JBSuppArc;
    private javax.swing.JButton JBSupprimerSource;
    private javax.swing.JMenuItem JMIArretertousSource;
    private javax.swing.JMenuItem JMIDemarrerTous;
    private javax.swing.JMenuItem JMIEnregister;
    private javax.swing.JMenuItem JMIExit;
    private javax.swing.JMenuItem JMIHistor;
    private javax.swing.JMenuItem JMILIgnebus;
    private javax.swing.JMenuItem JMINouveau;
    private javax.swing.JMenuItem JMIOuvrir;
    private javax.swing.JMenuItem JMIRetardBus;
    private javax.swing.JMenuItem JMIRetardBusEtVeh;
    private javax.swing.JMenuItem JMIRetardVeh;
    private javax.swing.JMenuItem JMISaveAs;
    private javax.swing.JMenuItem JMIvisualiser;
    private javax.swing.JMenu JMactions;
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JMenu JMenuFichier;
    private javax.swing.JTable JTABArcsEn;
    private javax.swing.JTable JTABArcsSor;
    private javax.swing.JTable JTABListeArcs;
    private javax.swing.JTable JTABListeCarrefours;
    private javax.swing.JTable JTabListeSources;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

}*/
