/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListeDesLignesJFrame.java
 *
 * Created on 8 sept. 2009, 21:43:16
 */

package Reseau;

import Agents.AgentReseau;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Dihya
 */
public class ListeDesLignesJFrame extends javax.swing.JFrame {

    VectorListModel model;
    AgentReseau AR;
    public ListeDesLignesJFrame(Vector<String> vect, AgentReseau ar) {
        initComponents();
        this.AR=ar;
        this.model=new VectorListModel(vect);
        this.JListeLignes.setModel(model);
        this.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListeLignes = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        JBFermer = new javax.swing.JButton();
        JBAjouter = new javax.swing.JButton();
        JBAfficher = new javax.swing.JButton();
        JBsuppLigne = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des lignes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane1.setViewportView(JListeLignes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        JBFermer.setText("Fermer");
        JBFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFermerActionPerformed(evt);
            }
        });

        JBAjouter.setText("Ajouter");
        JBAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterActionPerformed(evt);
            }
        });

        JBAfficher.setText("Afficher");
        JBAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAfficherActionPerformed(evt);
            }
        });

        JBsuppLigne.setText("Supprimer");
        JBsuppLigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsuppLigneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBAfficher, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBsuppLigne, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(JBFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(JBFermer)
                .addComponent(JBAjouter)
                .addComponent(JBAfficher)
                .addComponent(JBsuppLigne))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JBFermerActionPerformed

    private void JBAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterActionPerformed
        // TODO add your handling code here:
        String s = (String)JOptionPane.showInputDialog(
				   this,
				   "Saisir le code de la ligne",
				   "Ajout d'une nouvelle ligne",
				   JOptionPane.QUESTION_MESSAGE,
				   null,
				   null, // c'est ouvert !!!
				   null); // valeur initiale
		if ((s != null) && (s.length() > 0)){
            if (this.AR.AjouterAgentLigne(s)){
                this.model.raffraichir();
            }


		}
    }//GEN-LAST:event_JBAjouterActionPerformed

    private void JBAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAfficherActionPerformed
        // TODO add your handling code here:
        int i=this.JListeLignes.getSelectedIndex();
        if(i>=0){
            String nom=this.model.ListeLignes.elementAt(i);
            this.AR.Affichier_Interface(nom);
        }
    }//GEN-LAST:event_JBAfficherActionPerformed

    private void JBsuppLigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsuppLigneActionPerformed
        int i=this.JListeLignes.getSelectedIndex();
        if(i>=0){            
            this.AR.Lignes.ListeDesLigne.removeElementAt(i);
            this.AR.ListeLigne.removeElementAt(i);
            this.JListeLignes.repaint();
        }
    }//GEN-LAST:event_JBsuppLigneActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAfficher;
    private javax.swing.JButton JBAjouter;
    private javax.swing.JButton JBFermer;
    private javax.swing.JButton JBsuppLigne;
    private javax.swing.JList JListeLignes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
