/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AC_Gui.java
 *
 * Created on 8 août 2009, 21:58:11
 */

package Agents;

import Reseau.ComboBoxDialog;
import Reseau.DigrammePhases_TabModel;
import Reseau.ListeArcsCBModel;
import Reseau.ListeArcs_ListModel;
import Reseau.ListePhase_ListeModel;
import Reseau.ListeReservation_TabModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HACIANE
 */
public class AC_Gui extends javax.swing.JFrame {

    AgentCarrefour AC;
    ListePhase_ListeModel model_ListePhase;
    ListeArcs_ListModel model_ListeArcsEnt;
    ListeArcs_ListModel model_ListeArcsSort;
    DigrammePhases_TabModel model_diagrammePhase;
    ListeReservation_TabModel model_reservations;
    public AC_Gui(AgentCarrefour ac) {
        initComponents();
        this.AC=ac;
        this.model_ListePhase=new ListePhase_ListeModel(AC.Liste_Phases);
        this.JListe_ListePhases.setModel(model_ListePhase);
        this.JL_NomCarrefour.setText(AC.getLocalName());
        this.model_diagrammePhase=new DigrammePhases_TabModel(AC.Plan);
        this.model_reservations=new ListeReservation_TabModel(AC.Plan);
        this.JTabDiagrammePhases.setModel(this.model_diagrammePhase);
        this.JTABListeReservations.setModel(model_reservations);
        this.setTitle("Interface de l'agent carrefour ("+AC.getLocalName()+")");
        //
        if(this.AC.Plan.plan.size()>0){
            long d_deb=this.AC.Plan.plan.firstElement().date_d;
            long d_fin=this.AC.Plan.plan.lastElement().date_f;
            int cycle=(int) ((d_fin - d_deb) / 1000);
            this.JL_TailleCycle.setText(Integer.toString(cycle));
        }
        
        this.setVisible(true);
    }

    /* This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListe_ListePhases = new javax.swing.JList();
        JBAjouterPhase = new javax.swing.JButton();
        JBSuppPhase = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListe_ArcEnt = new javax.swing.JList();
        JB_AjouterArcEnt = new javax.swing.JButton();
        JB_SuppArcEnt = new javax.swing.JButton();
        JL_NomCarrefour = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JL_TailleCycle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTabDiagrammePhases = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTABListeReservations = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        JB_Fermer = new javax.swing.JButton();
        JB_Demarrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nom carrefour:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listes des phases du carrefour", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Phase");

        JListe_ListePhases.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JListe_ListePhasesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JListe_ListePhases);

        JBAjouterPhase.setText("+");
        JBAjouterPhase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAjouterPhaseActionPerformed(evt);
            }
        });

        JBSuppPhase.setText("-");
        JBSuppPhase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSuppPhaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JBSuppPhase, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(JBAjouterPhase, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAjouterPhase)
                    .addComponent(JBSuppPhase))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Arcs entrants");

        jScrollPane2.setViewportView(JListe_ArcEnt);

        JB_AjouterArcEnt.setText("+");
        JB_AjouterArcEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AjouterArcEntActionPerformed(evt);
            }
        });

        JB_SuppArcEnt.setText("-");
        JB_SuppArcEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SuppArcEntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(JB_SuppArcEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(JB_AjouterArcEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_AjouterArcEnt)
                    .addComponent(JB_SuppArcEnt))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        JL_NomCarrefour.setText("Nom");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Plan actuel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Taille du cycle:");

        JL_TailleCycle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JL_TailleCycle.setText(" ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Diagramme de phases:");

        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("secondes");

        JTabDiagrammePhases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(JTabDiagrammePhases);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_TailleCycle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JL_TailleCycle)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des réservations reçues", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        JTABListeReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(JTABListeReservations);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        JB_Fermer.setText("Fermer");
        JB_Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_FermerActionPerformed(evt);
            }
        });

        JB_Demarrer.setText("Démarrer");
        JB_Demarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_DemarrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(JB_Demarrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Fermer)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Fermer)
                    .addComponent(JB_Demarrer))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JL_NomCarrefour, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_NomCarrefour, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JListe_ListePhasesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JListe_ListePhasesValueChanged
        // TODO add your handling code here:
        int index=this.JListe_ListePhases.getSelectedIndex();
        if(index>=0){
            this.model_ListeArcsEnt=new ListeArcs_ListModel(AC.Liste_Phases.get(index).E);
            this.model_ListeArcsSort=new ListeArcs_ListModel(AC.Liste_Phases.get(index).S);
            this.JListe_ArcEnt.setModel(model_ListeArcsEnt);            
            this.model_ListeArcsEnt.raffraichir();
            this.model_ListeArcsSort.raffraichir();
        }

    }//GEN-LAST:event_JListe_ListePhasesValueChanged

    private void JBAjouterPhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAjouterPhaseActionPerformed
        // TODO add your handling code here:
        String s = (String)JOptionPane.showInputDialog(
				   this,
				   "Saisir le code de la phase à ajouter puis tapez ENTREE",
				   "Ajout d'une phase",
				   JOptionPane.QUESTION_MESSAGE,
				   null,
				   null, // c'est ouvert !!!
				   null); // valeur initiale
		if ((s != null) && (s.length() > 0)){
			this.AC.Ajouter_Phase(s);
            this.model_ListePhase.raffraichir();
		}else{
            //System.out.println("la phase "+s+" n'est pas créée !!");
        }
    }//GEN-LAST:event_JBAjouterPhaseActionPerformed

    private void JB_AjouterArcEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AjouterArcEntActionPerformed
        // TODO add your handling code here:
        int index_phase=this.JListe_ListePhases.getSelectedIndex();
        if(index_phase>=0){
            ListeArcsCBModel LACBM=new ListeArcsCBModel(this.AC.carrefour.E);
            ComboBoxDialog dial=new ComboBoxDialog(this, true, LACBM,"Ajouter arc", "selectionner un arc");
            if(dial.valider){
              int index=dial.selectedIndex;
              AC.Liste_Phases.elementAt(index_phase).E.addElement(this.AC.carrefour.E.get(index));
              this.model_ListeArcsEnt.raffraichir();
            }
            LACBM=null;
            dial=null;
        }
        
    }//GEN-LAST:event_JB_AjouterArcEntActionPerformed

    private void JBSuppPhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSuppPhaseActionPerformed
        // TODO add your handling code here:
        int index_phase=this.JListe_ListePhases.getSelectedIndex();
        if(index_phase>=0){
            AC.SuppPhase(index_phase);
            this.model_ListePhase.raffraichir();
        }
    }//GEN-LAST:event_JBSuppPhaseActionPerformed

    private void JB_SuppArcEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SuppArcEntActionPerformed
        // TODO add your handling code here:
        int index_phase=this.JListe_ListePhases.getSelectedIndex();
        if(index_phase>=0){
            int i=this.JListe_ArcEnt.getSelectedIndex();
            if (i>=0){
                this.AC.Liste_Phases.elementAt(index_phase).E.removeElementAt(i);
                this.model_ListeArcsEnt.raffraichir();
            }
        }
    }//GEN-LAST:event_JB_SuppArcEntActionPerformed

    private void JB_FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_FermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JB_FermerActionPerformed

    private void JB_DemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_DemarrerActionPerformed

        this.AC.demarrer();
    }//GEN-LAST:event_JB_DemarrerActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAjouterPhase;
    private javax.swing.JButton JBSuppPhase;
    private javax.swing.JButton JB_AjouterArcEnt;
    private javax.swing.JButton JB_Demarrer;
    private javax.swing.JButton JB_Fermer;
    private javax.swing.JButton JB_SuppArcEnt;
    private javax.swing.JLabel JL_NomCarrefour;
    public javax.swing.JLabel JL_TailleCycle;
    private javax.swing.JList JListe_ArcEnt;
    private javax.swing.JList JListe_ListePhases;
    private javax.swing.JTable JTABListeReservations;
    private javax.swing.JTable JTabDiagrammePhases;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

    public void raffraichir() {
        this.model_diagrammePhase.Raffraichir();
        this.model_reservations.fireTableDataChanged();
    }

}
